### ISSUE TITLE
ubuntu desktop + server NO GO

### ISSUE THREAD

**Issue by Zibri** [IsaacSchemm/MultiCD#70]
I tried using multicd to make a dual boot multicd with ubuntu server and ubuntu desktop.
Ubuntu desktop works but the ubuntu server installation does not start and any option does not work and bring back to menu

**Comment by IsaacSchemm** [comment]
What version of Ubuntu? 18.10? I can give it a try later.

**Comment by Zibri** [comment]
18.04.01 LTS

**Comment by IsaacSchemm** [comment]
It should work now. Let me know if there are still problems.

**Comment by Zibri** [comment]
Still a problem.
![image](https://user-images.githubusercontent.com/855176/50546310-86bbe300-0c2e-11e9-979d-319ef142e8f5.png)
I made multicd.iso using:
ubuntu-18.04.1-desktop-amd64.iso
and
ubuntu-18.04.1-live-server-amd64.iso
Then copied multicd.iso to /dev/sdd  (a 4gb pendrive)
I then booted it with qemu using:
$ sudo qemu-system-x86_64 -hda /dev/sdd -m 1024 -accel kvm

Selecting ubuntu desktop from the menu and then running "try ubuntu" as you can see from the screenshot there is not install ubuntu but install ubuntu server... like the two are mixed up...

**Comment by Zibri** [comment]
Please check it up... because even "install ubuntu" from the UBUNTU DESKTOP menu tries to install ubuntu server!

**Comment by IsaacSchemm** [comment]
Even though it says Ubuntu Server, I think that if you install it, it'll install Ubuntu Desktop. Haven't tried it yet though.

I'll see if I can change that label without breaking anything.

**Comment by IsaacSchemm** [comment]
Try again with the newest version. Both server and desktop installers should work.

**Comment by Zibri** [comment]
Just tested it.. now on Ubuntu desktop it says "Install Ubuntu (MultiCD)"
Tried installing both and they both work.
It would be even nicer if running the Ubuntu desktop LIVE, it could have 2 icons, one for installing ubuntu desktop and one for ubuntu server. That would be a great feature...

Anyway, well done.

**Comment by Zibri** [comment]
For reference, to test I used:

dd if=/dev/zero of=hdd.img bs=16M count=1k
qemu-system-x86_64 -hda hdd.img -cdrom multicd.iso -m 4096 -accel kvm

**Comment by IsaacSchemm** [comment]
Glad it works! Unfortunately I don't think I can add a second icon - as far as I know, the Ubuntu installer only works for the version of Ubuntu that's currently running.
